namespace Posseth.Toyota.Client.Models
{
    public class ExtendedCapabilities
    {
        public bool RemoteEngineStartStop { get; set; }
        public bool RemoteEConnectCapable { get; set; }
        public bool DoorLockUnlockCapable { get; set; }
        public bool FrontDriverDoorLockStatus { get; set; }
        public bool FrontPassengerDoorLockStatus { get; set; }
        public bool RearDriverDoorLockStatus { get; set; }
        public bool RearPassengerDoorLockStatus { get; set; }
        public bool FrontDriverDoorOpenStatus { get; set; }
        public bool FrontPassengerDoorOpenStatus { get; set; }
        public bool RearDriverDoorOpenStatus { get; set; }
        public bool RearPassengerDoorOpenStatus { get; set; }
        public bool FrontDriverDoorWindowStatus { get; set; }
        public bool FrontPassengerDoorWindowStatus { get; set; }
        public bool RearDriverDoorWindowStatus { get; set; }
        public bool RearPassengerDoorWindowStatus { get; set; }
        public bool RearHatchRearWindow { get; set; }
        public bool Moonroof { get; set; }
        public bool PowerWindowsCapable { get; set; }
        public bool HazardCapable { get; set; }
        public bool HornCapable { get; set; }
        public bool LightsCapable { get; set; }
        public bool ClimateCapable { get; set; }
        public bool ClimateTemperatureControlFull { get; set; }
        public bool ClimateTemperatureControlLimited { get; set; }
        public bool FrontDriverSeatHeater { get; set; }
        public bool FrontPassengerSeatHeater { get; set; }
        public bool RearDriverSeatHeater { get; set; }
        public bool RearPassengerSeatHeater { get; set; }
        public bool FrontDriverSeatVentilation { get; set; }
        public bool FrontPassengerSeatVentilation { get; set; }
        public bool RearDriverSeatVentilation { get; set; }
        public bool RearPassengerSeatVentilation { get; set; }
        public bool SteeringHeater { get; set; }
        public bool MirrorHeater { get; set; }
        public bool FrontDefogger { get; set; }
        public bool RearDefogger { get; set; }
        public bool VehicleFinder { get; set; }
        public bool GuestDriver { get; set; }
        public bool BuzzerCapable { get; set; }
        public bool TrunkLockUnlockCapable { get; set; }
        public bool EvChargeStationsCapable { get; set; }
        public bool FcvStationsCapable { get; set; }
        public bool LastParkedCapable { get; set; }
        public bool AcScheduling { get; set; }
        public bool ChargeManagement { get; set; }
        public bool NextCharge { get; set; }
        public bool WeeklyCharge { get; set; }
        public bool DailyCharge { get; set; }
        public bool PowerTailgateCapable { get; set; }
        public bool BatteryStatus { get; set; }
        public bool EvBattery { get; set; }
        public bool DrivePulse { get; set; }
        public bool ElectricPulse { get; set; }
        public bool HydrogenPulse { get; set; }
        public bool HybridPulse { get; set; }
        public bool EmergencyAssist { get; set; }
        public bool BumpCollisions { get; set; }
        public bool FuelLevelAvailable { get; set; }
        public bool FuelRangeAvailable { get; set; }
        public bool EquippedWithAlarm { get; set; }
        public bool ManualRearWindows { get; set; }
        public bool LightStatus { get; set; }
        public bool BonnetStatus { get; set; }
        public bool Sunroof { get; set; }
        public bool SmartKeyStatus { get; set; }
        public bool Ecare { get; set; }
        public bool TryAndPlay { get; set; }
        public bool DashboardWarningLights { get; set; }
        public bool WeHybridCapable { get; set; }
        public bool EnhancedSecuritySystemCapable { get; set; }
        public bool VehicleStatus { get; set; }
        public bool StellantisVehicleStatusCapable { get; set; }
        public bool StellantisClimateCapable { get; set; }
        public bool VehicleDiagnosticCapable { get; set; }
        public bool TelemetryCapable { get; set; }
        public bool EconnectClimateCapable { get; set; }
        public bool EconnectVehicleStatusCapable { get; set; }
    }
}